"""Screen taxonomy concepts for BASE-MODEL HEADROOM before spending GPU-hours minting them.

⚠ MEASURED 2026-08-25: THIS DOES NOT WORK. Do not wire it into the mint.
Run over 150 klein concepts, `low_poly_3d` — which produced null adapters on 4/4 replicates — scored
base_sim 0.248 against a taxonomy median of 0.245, i.e. the 53rd percentile. It is typical, not
extreme. Catching it requires a threshold below the median, which flags 69% of the corpus; any
defensible tail cut (10% -> 0.297, 20% -> 0.284) misses it. Base-model similarity does not separate
null adapters from good ones. The post-hoc `verify` gate remains the only thing that does. Kept for the
record so the idea is not silently retried.

Why this exists (measured, 2026-08-24). In the POC-M gate mint, 7 of 47 organisms were rejected as
"adapter adds nothing over the base model; likely a null adapter", and 4 of those 7 were every single
replicate of ONE concept, `low_poly_3d`. Its base similarity (0.239) was the highest of any failing
concept — the base klein model already renders low-poly well. Since training images are generated BY
that same base, a concept the base already knows leaves the LoRA nothing to learn: the loss-optimal
adapter is ~identity, so ΔW ≈ 0 and the organism is unusable. It is the self-distillation failure mode
recorded on 2026-08-12, resurfacing through concept SELECTION rather than through captions.

Why the fix is selection and not more training. The obvious repair — train weak concepts harder — is
BARRED here: `corpus_plan` fixes training steps as a function of dataset size only, precisely so that
step count cannot predict the label. Raising steps for concepts that come out null would make ‖ΔW‖ a
proxy for concept, which is the very confound the whole corpus design exists to remove. So the lever
has to be which concepts we mint, with the recipe held uniform.

What it does: render `--n-probe` images per concept from the BASE model, CLIP-score them against the
concept phrase, and report headroom = (concept phrase score) − (generic phrase score). Concepts whose
base score is already high have no room for an adapter to add signal, and are flagged DROP. Running
this costs ~7 s/image (klein at 4 steps), i.e. a few minutes for a whole taxonomy — against ~40 min
wasted per null organism.

Usage (on a mint box):
  PYTHONPATH=. python scripts/screen_concepts.py --n-concepts 60 --out assets/organisms/screen.json
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from ditloracle.mint import taxonomy

GENERIC = "a photograph"
# Base-similarity at or above which a concept is judged to have no headroom. Anchored on the measured
# failures: low_poly_3d sat at 0.239 and produced 4/4 null adapters, while art_nouveau_poster at 0.192
# trained fine in 4 of 6 replicates. The boundary between those is where this belongs; it is a
# measured threshold on this base model, NOT a universal constant — re-derive it per base.
BASE_SIM_DROP = 0.225


def screen(concepts, backend, n_probe: int = 4) -> list[dict]:
    rows = []
    for c in concepts:
        phrase = c.prompt_seed.replace("{}", "a subject")
        imgs = backend.render_base([phrase] * n_probe)
        base_sim = sum(backend.clip_score(im, phrase) for im in imgs) / max(len(imgs), 1)
        gen_sim = sum(backend.clip_score(im, GENERIC) for im in imgs) / max(len(imgs), 1)
        rows.append({
            "key": c.key,
            "family": c.family,
            "kind": c.kind,
            "base_sim": round(base_sim, 4),
            "generic_sim": round(gen_sim, 4),
            "headroom": round(base_sim - gen_sim, 4),
            "verdict": "DROP" if base_sim >= BASE_SIM_DROP else "keep",
        })
    return rows


def main() -> None:
    ap = argparse.ArgumentParser(description="Screen concepts for base-model headroom (cheap, pre-mint).")
    ap.add_argument("--n-concepts", type=int, default=None)
    ap.add_argument("--n-probe", type=int, default=4)
    # The DISTILLED checkpoint, because this measures what the base can RENDER. klein trains on the
    # `-base-` checkpoint but samples on the distilled one (PROGRESS 2026-08-13), and mint_run's
    # renderer defaults to exactly this repo — screening must match the renderer, not the trainer.
    ap.add_argument("--base-repo", default="black-forest-labs/FLUX.2-klein-4B")
    ap.add_argument("--out", default="assets/organisms/concept_screen.json")
    a = ap.parse_args()

    from scripts.mint_run import RealBackend

    concepts = taxonomy.resolve_concepts(a.n_concepts)
    backend = RealBackend(a.base_repo)
    rows = screen(concepts, backend, a.n_probe)
    backend.release()

    drop = [r for r in rows if r["verdict"] == "DROP"]
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(json.dumps({"base": a.base_repo, "threshold": BASE_SIM_DROP,
                                       "n_screened": len(rows), "n_drop": len(drop),
                                       "concepts": rows}, indent=2))
    print(f"screened {len(rows)} concepts -> {a.out}")
    print(f"  DROP (no headroom, base_sim >= {BASE_SIM_DROP}): {len(drop)}")
    for r in sorted(drop, key=lambda r: -r["base_sim"])[:15]:
        print(f"    {r['key']:34} base_sim={r['base_sim']}")


if __name__ == "__main__":
    main()
